Makefile, go.mod, pkg/backend/containerd/mounter.go, test/e2e/Dockerfile, test/e2e/driver.yaml, test/e2e/manifest.yaml
Show `lstat` of both sources and mountpoints if failed to mount.
=> More status on mount failures

Makefile, README.md, cmd/plugin/main.go, go.mod, install/cri-containerd-microk8s.yaml, install/cri-containerd.yaml, pkg/secret/cache.go, test/integration/test-in-minikube-containerd.sh
=> Supports Exec plugin

Makefile, cmd/plugin/node_server.go, hack/integration-test-image/csi-image-test:write-check.dockerfile, hack/integration-test-image/write_check.go, install/containerd-k3s.yaml, install/containerd-microk8s.yaml, install/containerd.yaml, install/cri-o.yaml, pkg/backend/containerd/containerd.go, pkg/backend/crio/crio.go, test/integration/manual-manifests/write-check.yaml, test/integration/minikube-bootlocal.sh, test/integration/restart-runtime.sh, test/integration/test-restart-runtime-containerd.sh, test/integration/test-restart-runtime-crio.sh
=> Reuse snapshots for restarted pods

Makefile, README.md, pkg/backend/mounter.go, test/e2e/README.md, test/e2e/driver.go, test/e2e/test.go, test/sanity/README.md, test/sanity/go.sum
Signed-off-by: Kitt Hsu <kitt.hsu@gmail.com>
=> Fix e2e and sanity tests

Makefile, cmd/install/main.go
This will make it easier to test local changes.
=> Allow to override the registry location.

README.md, cmd/install/main.go, cmd/plugin/main.go, cmd/plugin/node_server.go, hack/lib/cluster.sh, hack/lib/htpasswd, pkg/secret/cache.go, test/integration/cases.sh
=> Flag to disable the in-memory secret cache

pkg/secret/cache.go
=> use correct path for serviceAccount secret

Makefile, charts/warm-metal-csi-driver/Chart.yaml, charts/warm-metal-csi-driver/values.yaml
@mugdha-adhav  @kalpanathanneeru21 
I filed a new release on 0.6.x since the re-release v0.6.2 may lead to a git tag conflict.
=> Release v0.6.3

Makefile, charts/warm-metal-csi-driver/values.yaml
Creating a release for 0.6.4 with updated `Chart.yaml` and `Makefile`.
=> Release 0.6.4

charts/warm-metal-csi-driver/Chart.yaml
**Summary**
- Creating a release for v0.7.0 with updated Chart.yaml.
- Makefile is already updated, pointing to 0.7.0.
**TODO:**
- @kitt1987 needs to verify if the image for v0.7.0 is pushed to the container registry.
- After this PR is merged, cut a tag and create a release for v0.7.0.
Note: This would help us in releasing and deploying the new dynamic provisioner changes.
=> Update Chart.yaml version to v0.7.0

Makefile, charts/warm-metal-csi-driver/Chart.yaml, charts/warm-metal-csi-driver/templates/nodeplugin.yaml, charts/warm-metal-csi-driver/values.yaml, cmd/plugin/node_server.go, pkg/pullexecutor/pullexecutor.go
Combines https://github.com/warm-metal/csi-driver-image/pull/85 
Error looks like this:
=> fix: nil ptr err

.github/workflows/images.yaml
=> fix: Broken workflow for pushing images

README.md, cmd/install/cri.go, cmd/plugin/node_server.go, cmd/plugin/node_server_test.go, hack/integration-test-image/kind-node-image/Dockerfile, pkg/cri/client.go, pkg/pullexecutor/pullexecutor.go, pkg/remoteimage/pull.go, pkg/remoteimage/pull_test.go
=> chore: Use CRI v1 instead of v1alpha2

cmd/plugin/node_server_test.go, hack/ci/build.sh
Integration tests are failing due to an error introduced in [this](https://github.com/mugdha-adhav/csi-driver-image/commit/568db360ef24d4c6ef72374e507207347d122bd6) commit.
=> fix: failing integration tests

Makefile, charts/warm-metal-csi-driver/Chart.yaml
Updating chart.yaml and Makefile to `v1.0.0`.
=> Update Chart.yaml and Makefile to v1.0.0

.github/workflows/images-build-and-push.yaml, .github/workflows/images-cleanup.yaml, .github/workflows/stale.yaml, docs/automation.md
=> ci: Address outdated issues and PRs

.github/dependabot.yml, docs/automation.md
=> ci: Skip CI with dependabot updates

.github/workflows/cri-o.yaml, .github/workflows/restart-ds-crio.yaml, Makefile, test/e2e/manifest.yaml, test/integration/test-in-kind-crio.sh, test/sanity/manifest.yaml, test/unit/manifest.yaml, test/unit/skaffold.yaml
Related to #105.
Changes for updating references for old repository name in test files.
=> chore: update test manifests with new repo name

.devcontainer/devcontainer.json, .devcontainer/welcome.txt, .github/.devcontainer/Dockerfile, .github/.devcontainer/devcontainer.json, .github/workflows/devcontainer-build-and-push.yaml, docs/running-locally.md
=> 👷 build(devcontainer): Fix issue with multi-architecture

cmd/plugin/node_server.go
=> fix: improve error handling in NodeUnpublishVolume

Makefile, charts/warm-metal-csi-driver/Chart.yaml, charts/warm-metal-csi-driver/templates/nodeplugin.yaml, charts/warm-metal-csi-driver/values-crio.yaml, charts/warm-metal-csi-driver/values.yaml, cmd/plugin/main.go, cmd/plugin/node_server_test.go, pkg/metrics/metrics.go
=> Make metrics port configurable
